name: Test and Lint

on: push
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Lint with ruff
      run: |
        uv run ruff check
    - name: Test with pytest
      env:
        GITHUB_TOKEN: ${{ secrets.TESTS_GITHUB_TOKEN }}
      run: |
        uv run pytest
