name: Update Stable Docs

on:
  release:
    types: [published]
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update_stable_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"

      - name: Ensure stable branch exists
        run: |
          git fetch origin
          if ! git show-ref --verify --quiet refs/heads/stable; then
            git checkout -b stable
            git push origin stable
          fi

      - name: Handle Release
        if: github.event_name == 'release'
        run: |
          git fetch origin
          git checkout stable
          git reset --hard ${GITHUB_REF#refs/tags/}
          git push origin stable --force

      - name: Handle Commit to Main
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '!stable-docs')
        run: |
          git fetch origin
          git checkout stable
          # Get the list of modified files in docs/ from the current commit
          FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} -- docs/)
          if [[ -n "$FILES" ]]; then
            git checkout ${{ github.sha }} -- $FILES
            git add docs/
            git commit -m "Doc changes from ${{ github.sha }}"
            git push origin stable
          else
            echo "No changes to docs/ in this commit."
          fi